# SYS_CHROOT: sshd necesita jaula (privsep). Sin esto cierra la conexión.
# DAC_OVERRIDE/FOWNER: apt. NET_BIND_SERVICE: puerto 22.
# seccomp unconfined: auditctl (documentado; no es --privileged).
services:
  victima-linux:
    image: victima-linux-lab:clase03
    container_name: victima-linux
    hostname: victima-linux
    command: ["sleep", "infinity"]
    networks: [soc-net]
    ports:
      - "2222:22"
    cap_drop: ["ALL"]
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - AUDIT_CONTROL
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - SYS_CHROOT
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g
    volumes:
      - victima-logs:/var/log

volumes:
  victima-logs:

networks:
  soc-net:
    external: true
