
services:
  victima-linux:
    image: victima-linux-lab:clase03
    container_name: victima-linux
    hostname: victima-linux
    command: ["sleep", "infinity"]
    networks: [soc-net]
    ports:
      - "2222:22"
    cap_drop: ["ALL"]
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - AUDIT_CONTROL
      - AUDIT_WRITE
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g
    volumes:
      - victima-logs:/var/log

volumes:
  victima-logs:

networks:
  soc-net:
    external: true
